### ISSUE TITLE
Large client lag spike on spawning any E2 chip

### ISSUE THREAD

**Issue by Fasteroid** [Derpius/VisTrace#12]
**Describe the bug**
With the E2 Vistrace extension enabled, spawning/updating ANY expression chip will cause your client to freeze for a moment (700ms+).  Disabling the Vistrace E2 extension stops the lag spikes.  Speculating this is from acceleration structures being built regardless of the chip's content.

**To Reproduce**
1. Enable E2 Vistrace extension
2. Spawn any E2 chip to freeze for 700ms+

**Expected Behaviour**
Spawning chips shouldn't lag spike the client unless Vistrace is actually used in the chip and requires acceleration structures to be built.

**Comment by Andrew-Eathan** [comment]
nword lag 18 comfirmed
:trollface:

**Comment by Derpius** [comment]
Didn't notice any lag from building accel on my machine, but it's prob cause I have 12 threads, will make it only build accel when the rebuild command is called

**Comment by Derpius** [comment]
Fixed in f5d29c05dab356c7ee1c8ece2a19c9ddb2960972

**Comment by Fasteroid** [comment]
> will make it only build accel when the rebuild command is called
Thanks.
