### ISSUE TITLE
[bug] Error message on require() without the module

### ISSUE THREAD

**Issue by Vurv78** [Derpius/VisTrace#13]
**Describe the bug**
Thanks to garry, require() prints if a module was not found, even if pcalled!

**To Reproduce**
Steps to reproduce the behaviour:
1. Don't have vistrace
2. ``pcall(require, "Vistrace-0.x")``

**Expected behaviour**
Doesn't error

**Additional context**
https://github.com/Facepunch/garrysmod-issues/issues/5107
https://github.com/Facepunch/garrysmod-requests/issues/813

Starfall's patch: https://github.com/thegrb93/StarfallEx/blob/192f51a7e7a852a2613d34f26d441d4e49ca95ee/lua/starfall/sflib.lua#L612

**Comment by Derpius** [comment]
Fixed in 96094b3b3d9011cb2c791003c936eb14ee07cb3a
