### ISSUE TITLE
[feature] Microfacet thin specular reflection transmission

### ISSUE THREAD

**Issue by Derpius** [Derpius/VisTrace#58]
**Describe the solution you'd like**
Reimplement yocto-gl's thin microfacet BSDF in the new system.

**Comment by yogwoggf** [comment]
If it helps NVIDIA has implemented a thin microfacet BTDF along with a normal thin BTDF.
https://github.com/NVIDIA/MDL-SDK/blob/2a00fa2bb85bdb184b12ce7e00d02f6cbc81bb5c/src/mdl/jit/libbsdf/libbsdf.cpp

**Comment by Derpius** [comment]
I’ll be implementing it from yocto-gl
