### ISSUE TITLE
[feature] Replace stack-based material reading with IMaterial

### ISSUE THREAD

**Issue by Derpius** [Derpius/VisTrace#70]
**Is your feature request related to a problem? Please describe.**
The current method for reading `IMaterial` properties off the stack is cumbersome and inefficient.

**Describe the solution you'd like**
Implement the real `IMaterial` class in order to interface with the userdata directly.

**Additional context**
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/materialsystem/imaterial.h#L446-L604

**Comment by yogwoggf** [comment]
Got the implementation in C++ fully working. Going to make everything use it 😘😏
