### ISSUE TITLE
[feature] Copy constructor for IRenderTarget

### ISSUE THREAD

**Issue by yogwoggf** [Derpius/VisTrace#82]
**Is your feature request related to a problem? Please describe.**
My post-processing VisTrace extension relies a lot on rendertargets, so it'd be beneficial for me to be able to copy IRenderTargets around.

**Describe the solution you'd like**
I want a copy constructor to be added to IRenderTarget which would 

**Describe alternatives you've considered**
There is no (good) alternative to this.

**Comment by yogwoggf** [comment]
Just some quick researching before implementing.. virtual copy constructors don't exist :trollface:

**Comment by Derpius** [comment]
The interface class shouldn’t have a copy constructor, the derived class should…
